version: '3.9'

services:

  frontend:
    build: frontend
    ports:
      - 8081:80
    volumes:
      - ./:/app

  backend:
    build: backend
    ports:
      - 8080:80
    volumes:
      - ./:/app

  mysql_dev:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_dev
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_user
    ports:
      - 3306:3306
    volumes:
      - ./mysql_dev_cache:/var/lib/mysql